/-
  LavaLamp — Lean 4 formal-verification scaffold.

  Per CLAUDE.md package-management discipline:
    "Lean4 | lean-toolchain + lake-manifest.json"
    "verify a clean checkout + lockfile install builds before committing"

  Toolchain pinned in `lean-toolchain` (currently
  leanprover/lean4:v4.18.0).

  No external dependencies at the scaffold tier. When round-3
  architectural decisions land, this lakefile gains either a
  Mathlib `require` (for Real / probability / measure-theoretic
  proofs) or project-local replacements for the small subset of
  Mathlib we actually need. The decision is round-3-driven; see
  `README.md` §Mathlib integration for the discipline note.

  Lockfile: `lake-manifest.json` is regenerated by `lake update`;
  bootstrap from a clean checkout via:

      cd src/lean4
      lake update
      lake build

  At the scaffold tier the manifest is empty (no dependencies);
  it will gain entries when round-3 lands and proofs begin.
-/

import Lake
open Lake DSL

package «LavaLamp» where
  -- Default leanOptions; production-grade settings land with the
  -- first real proof work.
  leanOptions := #[
    ⟨`pp.unicode.fun, true⟩,
    ⟨`autoImplicit, false⟩
  ]

@[default_target]
lean_lib «LavaLamp» where
  -- Library root is `LavaLamp.lean`; submodule files live under
  -- `LavaLamp/`.
  defaultFacets := #[LeanLib.leanArtsFacet]
